---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars[groups['swarm-manager'][0]].worker_token }}"
    remote_addrs: "{{ groups['swarm-manager'][0] }}"
  tags: swarm
  when: swarm_status.rc != 0

